api = "0.9"

[buildpack]
id = "jkutner/sshd"
version = "0.2.0"
name = "SSH Server Buildpack"
homepage = "https://github.com/jkutner/sshd-buildpack"
description = "Configures and run sshd in the container"
keywords = ["sshd", "ssh", "shell"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"
